apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    sealos-db-provider-cr: fullstack
    app.kubernetes.io/instance: fullstack
    app.kubernetes.io/managed-by: kbcli
  name: fullstack

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    sealos-db-provider-cr: fullstack
    app.kubernetes.io/instance: fullstack
    app.kubernetes.io/managed-by: kbcli
  name: fullstack
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    sealos-db-provider-cr: fullstack
    app.kubernetes.io/instance: fullstack
    app.kubernetes.io/managed-by: kbcli
  name: fullstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fullstack
subjects:
  - kind: ServiceAccount
    name: fullstack